<html><head><meta http-equiv=Content-Type content='text/html; charset=utf-8'></head>
var default_view =0;var htmlStr = '<link rel="stylesheet" type="text/css" href="skin/green/style.css" tppabs="http://www.hnwxdl.com/plugins/lineservice/skin/green/style.css" />'
+ '<scr'+'ipt type="text/javascript" src="js/jquery.lazyload.min.js" tppabs="http://www.hnwxdl.com/plugins/lineservice/js/jquery.lazyload.min.js"></sc'+'ript>'
+ '<scr'+'ipt type="text/javascript" src="js/script.js" tppabs="http://www.hnwxdl.com/plugins/lineservice/js/script.js"></sc'+'ript>'
+ '<div id="WOSBtn_wx" style="position: absolute; display: block; right: 1px; top: 156px;width: 126px; height: 500px; z-index: 1000;">'
+ '<div id="BtnQQ" class="online-left online-hidden">'
+ '</div>'
+ '<div class="online-right">'
+ '<a class="online_M online-tc" id="bqq2"></a>'
+ '<ul class="online-phone">'
+ '<li>'
+ '<div class="phone-name">前台客服</div>'
+ '<div class="phone-nub" style="text-align: center;">'
+ '<a target="_blank" href="tencent://message/?uin=394007749&Site=&Menu=yes" title=394007749">394007749</a>'
+ '</div></li>'
+ '</ul>'
+ '<div class="online-tel"> 0371-55693699</div>'
+ ' <div class="kwfwexin"><img src="../../uploads/201507/18/201507180920210891.jpg" tppabs="http://www.hnwxdl.com/uploads/201507/18/201507180920210891.jpg" ></div>'
+ '</div>'
+ '</div>'
document.write(htmlStr);
